site_name: Channels Easy
site_url: https://namantam1.github.io/channels-easy/
site_author: Naman Tamrakar

# Repository
repo_name: namantam1/channels-easy
repo_url: https://github.com/namantam1/channels-easy/
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2021-2022 Naman Tamrakar

nav:
  - Home: index.md
  - API Reference: apis.md

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings
